@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/

### AppControllerGetHello1
# @name AppControllerGetHello1
GET {{baseUrl}}/home/hello1

### ConceitosManualControllerHome
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoControllerHome
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/

### RecadosControllerFindAll
# @name RecadosControllerFindAll    
GET {{baseUrl}}/recados/
?limit=300
&offset=200

### RecadosControllerCreate
# @name RecadosControllerCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "E agora, quem poderá me defender?",
  "de": "Davi",
  "para": "Golias",
  "lido": false,
  "data": "2026-01-17T00:54:47.261Z"
}

### RecadosControllerFindOne
# @name RecadosControllerFindOne
GET {{baseUrl}}/recados/1

### RecadosControllerUpdate     
# @name RecadosControllerUpdate
PUT {{baseUrl}}/recados/3
Content-Type: application/json

  {
    "texto": "Te pego no flagra!",
    "de": "Alice",
    "para": "Bob",
    "lido": false,
    "data": "2026-01-17T02:08:40.895Z"
  }

### RecadosControllerPatch
# @name RecadosControllerPatch
PATCH {{baseUrl}}/recados/125
Content-Type: application/json

{
  "title": "Novo Recado",
  "description": "Descrição do novo recado"
}

### RecadosControllerDelete
# @name RecadosControllerDelete
DELETE {{baseUrl}}/recados/6
Content-Type: application/json